FROM datajoint/djbase:py3.9-debian-fcd8909

USER anaconda:anaconda

COPY ./workflow-array-ephys/docker/apt_requirements.txt /tmp/
RUN /entrypoint.sh echo "Installed dependencies."

RUN mkdir /main/element-lab \
          /main/element-animal \
          /main/element-session \
          /main/element-trial \
          /main/element-array-ephys \
          /main/workflow-array-ephys

# Copy user's local fork of elements and workflow
COPY --chown=anaconda:anaconda ./element-lab /main/element-lab
COPY --chown=anaconda:anaconda ./element-animal /main/element-animal
COPY --chown=anaconda:anaconda ./element-session /main/element-session
COPY --chown=anaconda:anaconda ./element-trial /main/element-trial
COPY --chown=anaconda:anaconda ./element-electrode-localization /main/element-electrode-localization
COPY --chown=anaconda:anaconda ./element-array-ephys /main/element-array-ephys
COPY --chown=anaconda:anaconda ./workflow-array-ephys /main/workflow-array-ephys

# Install packages
RUN pip install -e /main/element-lab
RUN pip install -e /main/element-animal
RUN pip install -e /main/element-session
RUN pip install -e /main/element-trial
RUN pip install -e /main/element-electrode-localization
RUN pip install -e /main/element-array-ephys
RUN pip install -e /main/workflow-array-ephys
RUN pip install -r /main/workflow-array-ephys/requirements_test.txt

WORKDIR /main/workflow-array-ephys

ENTRYPOINT ["tail", "-f", "/dev/null"]
